### PR TITLE
chooify the static site

### PR DESCRIPTION
**Pull request by karissa**
not ready! still needs style updates etc.

### CODE REVIEW

**Comment by karissa** [comment]
ok this is ready for your style mastery @Kriesse

**Comment by karissa** [comment]
@yoshuawuyts is there a nice way to read in these `.md` files and use them in the blog posts without having to wrap them in a function call? I tried using `brfs` with `fs` with no luck

**Comment by Kriesse** [comment]
@karissa Can you help to get the latest changes from master merged into this? Wanted to pick up work here but wasn't quite sure about the merge conflicts.

**Comment by yoshuawuyts** [comment]
@karissa this is how I'm doing markdown to html in `choo-handbook`: https://github.com/yoshuawuyts/choo-handbook/blob/master/index.js - there's some bugs in there tho, need to figure it out still

**Comment by karissa** [comment]
@Kriesse ok, fixed merge conflicts but lets wait until after the desktop app release before working on this. This chooification can be part of the next release (user accounts)

**Comment by Kriesse** [comment]
@karissa cool, sounds good!

**Comment by karissa** [comment]
ok @Kriesse this is ready to go for you, when you are

**Comment by karissa** [comment]
also makes it so we only have one css file. @Kriesse ready for your review!

**Comment by Kriesse** [comment]
@karissa Fixed a few small visual issues, everything else seems to be fine!

**Comment by yoshuawuyts** [comment]
Currently navigating to `/blog` is broken; it complains about `fs` not being found which makes me suspect `brfs` isn't running the way it should. cc/ @karissa

**Comment by karissa** [comment]
OK Blog fixed!

**Comment by karissa** [comment]
Nice catch @yoshuawuyts !

**Pull request merged**
